const SUBMITTED = "SUBMITTED";
const CONFIRMED = "CONFIRMED";
const COOKING = "COOKING";
const READY = "READY";
const BILLED = "BILLED";

const ORDER_STATUS = {
  SUBMITTED,
  CONFIRMED,
  COOKING,
  READY,
  BILLED
};

module.exports = {
  ORDER_STATUS,
  SUBMITTED,
  CONFIRMED,
  COOKING,
  READY,
  BILLED
};